### ISSUE TITLE
It appears that you do not have permission to access the requested resource.

### ISSUE THREAD

**Issue by AminMoradiXL** [1ssb/torchkan#7]
I get this error after I run the mnist.py code. I have created wandb account and logged in. Your help is appreciated! 
```
wandb: Currently logged in as: aminmoradixl. Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: permission denied (<Response [403]>)
Traceback (most recent call last):

  File ~/anaconda3/envs/pykan/lib/python3.9/site-packages/spyder_kernels/customize/spyderpdb.py:900 in run
    super(SpyderPdb, self).run(cmd, globals, locals)

  File ~/anaconda3/envs/pykan/lib/python3.9/bdb.py:580 in run
    exec(cmd, globals, locals)

  File ~/kan_chaos/torchkan/mnist.py:17
    wandb.init(project="quantized_model_evaluation", entity="aminmoradixl")

  File ~/anaconda3/envs/pykan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py:1185 in init
    wandb._sentry.reraise(e)

  File ~/anaconda3/envs/pykan/lib/python3.9/site-packages/wandb/analytics/sentry.py:155 in reraise
    raise exc.with_traceback(sys.exc_info()[2])

  File ~/anaconda3/envs/pykan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py:1171 in init
    return wi.init()

  File ~/anaconda3/envs/pykan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py:776 in init
    raise error

CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)```

**Comment by 1ssb** [comment]
You must use your own wandb login.
________________________________
From: AminMoradiXL ***@***.***>
Sent: Friday, June 14, 2024 8:43:59 AM
To: 1ssb/torchkan ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [1ssb/torchkan] It appears that you do not have permission to access the requested resource. (Issue #7)


I get this error after I run the mnist.py code. I have created wandb account and logged in.

wandb: Currently logged in as: aminmoradixl. Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: permission denied (<Response [403]>)
Traceback (most recent call last):

  File ~/anaconda3/envs/pykan/lib/python3.9/site-packages/spyder_kernels/customize/spyderpdb.py:900 in run
    super(SpyderPdb, self).run(cmd, globals, locals)

  File ~/anaconda3/envs/pykan/lib/python3.9/bdb.py:580 in run
    exec(cmd, globals, locals)

  File ~/kan_chaos/torchkan/mnist.py:17
    wandb.init(project="quantized_model_evaluation", entity="aminmoradixl")

  File ~/anaconda3/envs/pykan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py:1185 in init
    wandb._sentry.reraise(e)

  File ~/anaconda3/envs/pykan/lib/python3.9/site-packages/wandb/analytics/sentry.py:155 in reraise
    raise exc.with_traceback(sys.exc_info()[2])

  File ~/anaconda3/envs/pykan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py:1171 in init
    return wi.init()

  File ~/anaconda3/envs/pykan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py:776 in init
    raise error

CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)```

**Comment by AminMoradiXL** [comment]
If you mean here: 
```# Initialize Weights & Biases for experiment tracking and visualization
wandb.init(project="quantized_model_evaluation", entity="aminmoradixl")
```
I already did.

**Comment by 1ssb** [comment]
Have you set up your wandb username and initialised the login? 
Test it on something simple. Use a different project name. This is unrelated to the implementation, you might be a bit on your own here.
