### ISSUE TITLE
About the interpretability

### ISSUE THREAD

**Issue by kaneyxx** [1ssb/torchkan#8]
Hi, thanks for sharing these implementations for high-dimenationality data. I'm not familiar about these basic theorem behind implementations. Just curious if these new nets have same interpretability as original KAN?

**Comment by 1ssb** [comment]
I am currently delayed in releasing the detailed documentation but just to understand the basis functions you may consider the following:

1. Chebyshev approximation
2. Legendre approximation
3. Fourier approximation

These are extremely well documented ideas and hence require no additional novel analysis as such, the way we are utilising this are a little loose but you may consider them as motivations.

https://teaching.smp.uq.edu.au/scims/Num_analysis/Polynomial.html

Now, coming to your more interesting question, what are the implications in higher dimensions ---not much at least mathematically. What we do have however are intuitive hypotheses, for example the MNIST or CIFAR datasets for example are large dimensions but the data would possibly lie in low dimensional spaces and those are being approximated by these basis functions working in a multilinear fashion, which are simpler and explicit. Whether these hold for perturbations etc is an open question.

**Comment by kaneyxx** [comment]
Thanks for answering and sharing the information. I will take a look. I agree with you, so the better approach (currently) for high dimensions is to use a transformation matrix to convert the data to lower dimensions (if they fit the hypothesis), and then use KAN for interpretation. Right?

**Comment by 1ssb** [comment]
As alluring as it may be, using words like transformation are not technically correct; I suggest not using them because they really are not mathematical transformations, at best they are a map. But yes you are right, intuitively at least.

**Comment by kaneyxx** [comment]
Yes, I still aspire to interpret high-dimensional data directly with a KAN-based approach. Perhaps I need to study the information you provided at first. Thank you very much!
